name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Self test
        uses: ElliotLuque/check-total-mouredev-challenges@master
